### ISSUE TITLE
Implement a "save" functionality

### ISSUE THREAD

**Issue by ivanbatic** [rabix/cottontail#24]
When editing files, we need to be able to persist the current state of the file.

**Comment by ivanbatic** [comment]
When the file is supposed to be saved, it isn't. The backend returns the 404 error.

**Comment by mayacoda** [comment]
@ivanbatic I couldn't reproduce this error. Could you provide more details?

**Comment by ivanbatic** [comment]
@mayacoda I can't reproduce it anymore, probably fixed in the meantime.

**Comment by ivanbatic** [comment]
I cannot save files that are not in the root of the project.
Payload:
`"updateFile",{"file":"assets/sass/_mixins.scss","content":"@import \"~bootstrap/scss/mixins\";\n\n"}`

Response:
`[{"statusCode":404,"error":"Not Found"}]`

**Comment by mayacoda** [comment]
Should be fixed with https://github.com/rabix/cottontail/commit/3c2c4620446060cb3440327e7e5f4b8e3123e376
