### ISSUE TITLE
Create files through context menu actions

### ISSUE THREAD

**Issue by ivanbatic** [rabix/cottontail#26]
At the moment, new files are created by clicking on the "New File" button, then specifying the file name.
File system is a tree, and it would be very impractical to make users type in the full path to nested directory they want to put the new file into.

I suggest we create a context menu for the file tree; right clicking on folders would bring up the list of actions, amongst which would be the "New File..." action.

**Comment by mayacoda** [comment]
+1 for the context menu. It's a useful place to add functionalities like copying/duplicating a file and eventually run and validate.

**Comment by mayacoda** [comment]
Implemented in #57 by @ivanbatic.
