### ISSUE TITLE
Detect a difference between a working copy of a file and the file system version

### ISSUE THREAD

**Issue by ivanbatic** [rabix/cottontail#28]
If the working copy of a file (what users see in the editor) differs from its original state in the system, it should be visually indicated; probably with an asterisk sign in the tab title.

**Comment by mayacoda** [comment]
Related to https://github.com/rabix/cottontail/issues/29

**Comment by mayacoda** [comment]
@ivanbatic, @matesk8: We should discuss how we'll proceed with architecture before implementing specific features like this one. I'm afraid we might end up with a lot of sloppy, inconsistent code.

**Comment by mayacoda** [comment]
@ivanbatic: this has somewhat been implemented, right? The user has an indication if a file has been edited since it was loaded. Can you check if you're satisfied and close this issue?
