### ISSUE TITLE
Create a CWL validator

### ISSUE THREAD

**Issue by ivanbatic** [rabix/cottontail#43]
The validator should be relatively optimal in terms of feedback speed.
The errors are to be reported to the user in the Ace editor.

**Comment by mayacoda** [comment]
For now, errors will be displayed in an errors console. In the future, we'll add inline validation inside the code editor.

**Comment by mayacoda** [comment]
Also, validation will work kind of like this:
- JSON schema validation as a first line of defense. This type of validation will reveal obvious errors, ones that make the description not CWL.
- After a tool has passed JSON schema validation, that means it's the proper format to be loaded into the model. The model will then return semantic validation errors, if any.
- If the file is changed via text mode, tool goes through JSON schema validation again and is reloaded into the model
- If the tool is changed via GUI mode, the model handles realtime semantic validation and does not allow for an invalid CWL tool to be created.

**Comment by mayacoda** [comment]
Closing in favor of discussion on https://github.com/rabix/cwl-ts
